name       : kxmlgui
version    : 5.60.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kxmlgui-5.60.0.tar.xz : c81c2794610add13fd8019031fb40b0d002085d40ba358f6406c54f79581c149
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
