name       : kxmlgui
version    : 5.46.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kxmlgui-5.46.0.tar.xz : 3421b1dde58022586b7ae1c2d06ce3042e1ce043ea4ad800e1ba0b3787cf9d73
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
