name       : kxmlgui
version    : 5.58.0
release    : 34
source     :
    - https://download.kde.org/stable/frameworks/5.58/kxmlgui-5.58.0.tar.xz : ab08ed118f6806154fe10414d81dace413ecf80df3a561811f41879b48b7179f
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
