name       : kxmlgui
version    : 5.64.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kxmlgui-5.64.0.tar.xz : faa95b92b3b03130022841a6797d5beb3efb6a0d757afaefe038889af76a1dd1
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
