name       : kxmlgui
version    : 5.76.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kxmlgui-5.76.0.tar.xz : 73ae838fb79f97243bea36d438e9bc45315183bbb6b08ab5173c822cfcb4dd82
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
