name       : kxmlgui
version    : 5.65.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kxmlgui-5.65.0.tar.xz : 1de343bd51ba57053fd30eefb2237fb022b7cc274be6132fb9064bec64c39e95
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
