name       : kxmlgui
version    : 5.42.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kxmlgui-5.42.0.tar.xz : c01715eb7ba54e10ef3754ac2fd2de580ad6b12568dbe657d17ec2cc5197dd4d
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
