name       : kxmlgui
version    : 5.57.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kxmlgui-5.57.0.tar.xz : 325124518e8fa4847c898dee193d96b76a7ba27d7c79d875f34c632f46fe1f90
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
