name       : kxmlgui
version    : 5.83.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kxmlgui-5.83.0.tar.xz : 1be50b7dd9ada03754a64409ec678feede0ad9ca73dd978093ebbd552bf7c3d6
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kconfig-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
