name       : kxmlgui
version    : 5.91.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/kxmlgui-5.91.0.tar.xz : 2f68b187570e22c7037fdbcff83ebaad8b5c77fe1bec166c059da6d475149ce3
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kconfig-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
