name       : kxmlgui
version    : 5.63.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kxmlgui-5.63.0.tar.xz : f1a0b8e72da813251f22b675e5f1596d2675c41eb02a8aa8ea8423faae721574
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
