name       : kxmlgui
version    : 5.106.0
release    : 78
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kxmlgui-5.106.0.tar.xz : 44af980c2c6fcb5922c6809c4df32200ba2008cf25c0c48236dad31a947f18aa
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kconfig-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
