name       : kxmlgui
version    : 5.35.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.35/kxmlgui-5.35.0.tar.xz : a59df51f7ae514ff94d3989707d20e761569cc819d834182b7f56810305060e8
license    : LGPL-2.1
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - attica-devel
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
