name       : kxmlgui
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kxmlgui-5.25.0.tar.xz : 1ff1f07fc1bede0cb0b498de2d2b0db088639b91d0f7c39a90abfc032dbb44b2
license    : LGPL-2.1
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBEXECDIR=%libdir% \
           -DFORCE_DISABLE_KGLOBALACCEL=TRUE .
build      : |
    %make
install    : |
    %make_install
