name       : kxmlgui
version    : 5.74.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kxmlgui-5.74.0.tar.xz : c5601a811c5d680b370ccf0388de71a49af090718b5f25716c38ce9689c783a1
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
