name       : kxmlgui
version    : 5.70.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kxmlgui-5.70.0.tar.xz : 0ef58f324d4cfbc625ce5baee6ea410a57078140cb6de81c60097dd604667f33
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - attica-devel
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
