name       : kxmlgui
version    : 5.85.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kxmlgui-5.85.0.tar.xz : 253ae3984f2cc68165c683f5ac1f0a0417923d13673354e7ac8f156542cd3cb2
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kconfig-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
